deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
  limits_config:
    allow_structured_metadata: false

singleBinary:
  replicas: 1

gateway:
  enabled: true
  replicas: 1

# Explicitly disable all distributed components
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
ingester:
  replicas: 0
distributor:
  replicas: 0
indexGateway:
  replicas: 0
compactor:
  replicas: 0
ruler:
  replicas: 0

# Disable all caching components
chunksCache:
  enabled: false
  
resultsCache:
  enabled: false

# Disable monitoring components
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  serviceMonitor:
    enabled: false
  lokiCanary:
    enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false

minio:
  enabled: false 