config:
  clients:
    - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push

  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod

      pipeline_stages:
        # Automatic JSON parsing - works with any JSON structure
        - json:
            expressions: {}
        
        # Extract timestamp if available
        - timestamp:
            format: RFC3339Nano
            source: timestamp
        
        # Alternative timestamp formats for Laravel
        - timestamp:
            format: '2006-01-02T15:04:05.999999Z07:00'
            source: datetime
            
        # Add common labels for filtering
        - labels:
            level: level
            level_name: level_name
            channel: channel
            method: method
            route: route
            status: status
            user_id: user_id
            request_id: request_id
            trace_id: trace_id

      relabel_configs:
        # Only scrape pods with annotation
        - action: keep
          regex: true
          source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            
        # Add namespace label
        - source_labels:
            - __meta_kubernetes_namespace
          target_label: kubernetes_namespace
          
        # Add pod name label
        - source_labels:
            - __meta_kubernetes_pod_name
          target_label: kubernetes_pod_name
          
        # Add container name label
        - source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: kubernetes_container_name
          
        # Add app label
        - source_labels:
            - __meta_kubernetes_pod_label_app
          target_label: app

    # For pods without annotations (system pods, etc.)
    - job_name: kubernetes-pods-static
      kubernetes_sd_configs:
        - role: pod

      pipeline_stages:
        - json:
            expressions: {}

      relabel_configs:
        # Skip pods that have the scrape annotation (handled by first job)
        - action: drop
          regex: true
          source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            
        # Add standard labels
        - source_labels:
            - __meta_kubernetes_namespace
          target_label: kubernetes_namespace
        - source_labels:
            - __meta_kubernetes_pod_name
          target_label: kubernetes_pod_name
        - source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: kubernetes_container_name 