# Simplified Percona XtraDB Cluster values
# Production-ready MySQL cluster with MinIO backups + PITR

# Basic cluster configuration
crVersion: 1.18.0
enableCRValidationWebhook: false

# TLS configuration - disabled for simplicity
tls:
  enabled: false

# Unsafe flags to disable TLS requirement
unsafeFlags:
  tls: true

# MySQL configuration
pxc:
  size: 3
  image:
    repository: percona/percona-xtradb-cluster
    tag: 8.0.42-33.1
  
  # Resource allocation per pod
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
  
  # Persistence
  volumeSpec:
    persistentVolumeClaim:
      storageClassName: do-block-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
  
  # MySQL configuration
  configuration: |
    [mysqld]
    wsrep_provider_options="debug=0;gcache.size=300M;gcache.keep_pages_size=300M"
    wsrep_debug=0
    wsrep_cluster_name=cluster1
    binlog_format=ROW
    default_storage_engine=InnoDB
    innodb_autoinc_lock_mode=2
    innodb_locks_unsafe_for_binlog=1
    max_connections=1024
    innodb_buffer_pool_size=512M
    
    # Binary logging for PITR
    log-bin=mysql-bin
    binlog_expire_logs_seconds=604800
    max_binlog_size=100M
    sync_binlog=1
    
    # GTID for consistent backups
    gtid_mode=ON
    enforce_gtid_consistency=ON
    log_slave_updates=ON
  
  # Security context
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    
  # Anti-affinity to spread pods across nodes
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - percona-xtradb-cluster
        topologyKey: kubernetes.io/hostname

# HAProxy configuration
haproxy:
  enabled: true
  size: 2
  
  # Resource allocation
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
      
  # Service configuration - cluster-internal by default
  serviceType: ClusterIP
  
  # Anti-affinity for HAProxy pods
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - percona-xtradb-cluster-haproxy
          topologyKey: kubernetes.io/hostname

# Pod Disruption Budget to protect quorum
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

# Backup configuration with MinIO + PITR
backup:
  enabled: true
  
  # Daily full backup schedule
  schedule:
    - name: daily-backup
      schedule: "0 2 * * *"
      keep: 7
      storageName: minio-storage
      
  # PITR configuration - binlog backups every 60s
  pitr:
    enabled: true
    storageName: minio-storage
    timeBetweenUploads: 60
    
  # MinIO storage configuration  
  storages:
    minio-storage:
      type: s3
      s3:
        bucket: db-backup
        region: us-east-1
        endpointUrl: https://minio.terapeas.com
        credentialsSecret: minio-backup-secret
        # Use path-style access for MinIO compatibility
        forcePathStyle: true

# Monitoring (disable for simplicity)
pmm:
  enabled: false