apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  # Production credentials
  # Username: minioadmin (base64: bWluaW9hZG1pbg==)
  # Password: Mpft0qBAEX2yIFXCqe/Ez5kAXZ89cabLEzI90jMtCRg= (base64: TXBmdDBxQkFFWDJ5SUZYQ3FlL0V6NWtBWFo4OWNhYkxFekk5MGpNdENSZz0=)
  MINIO_ROOT_USER: bWluaW9hZG1pbg==
  MINIO_ROOT_PASSWORD: TXBmdDBxQkFFWDJ5SUZYQ3FlL0V6NWtBWFo4OWNhYkxFekk5MGpNdENSZz0=