apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-octane.fullname" . }}
  labels:
    {{- include "laravel-octane.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-octane.selectorLabels" . | nindent 6 }}
      octane.laravel.com/pod-type: web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-octane.selectorLabels" . | nindent 8 }}
        octane.laravel.com/pod-type: web
    spec:
      volumes:
        - name: env
          secret:
            secretName: {{ if .Values.app.envSecretName }} {{ .Values.app.envSecretName }} {{ else }} {{ .Release.Name }}-env {{ end }}
        - name: php-ini-config
          configMap:
            name: {{ if .Values.phpIni.configName }} {{ .Values.phpIni.configName }} {{ else }} {{ .Release.Name }}-php-ini-config {{ end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "laravel-octane.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: octane
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command:
            {{- toYaml .Values.app.command | nindent 12 }}
          volumeMounts:
            - name: env
              mountPath: /tmp/.env
              subPath: .env
            - name: php-ini-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            {{- with .Values.app.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.app.healthcheck.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.healthcheck.period }}
            periodSeconds: {{ .Values.app.healthcheck.period }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.app.healthcheck.period }}
            periodSeconds: {{ .Values.app.healthcheck.period }}
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- with .Values.app.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /tmp/.env /var/www/html/.env && cd /var/www/html && if [ -f post-start.sh ]; then sh post-start.sh; fi
        {{- if .Values.scheduler.enabled }}
        - name: scheduler
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command:
            {{- toYaml .Values.scheduler.command | nindent 12 }}
          volumeMounts:
            - name: env
              mountPath: /tmp/.env
              subPath: .env
            - name: php-ini-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            {{- with .Values.app.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.scheduler.healthcheck.enabled }}
          readinessProbe:
            exec:
              command:
                - php
                - -v
            initialDelaySeconds: {{ .Values.scheduler.healthcheck.period }}
            periodSeconds: {{ .Values.scheduler.healthcheck.period }}
          livenessProbe:
            exec:
              command:
                - php
                - -v
            initialDelaySeconds: {{ .Values.scheduler.healthcheck.period }}
            periodSeconds: {{ .Values.scheduler.healthcheck.period }}
          {{- end }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          {{- with .Values.app.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /tmp/.env /var/www/html/.env && cd /var/www/html && if [ -f post-start.sh ]; then sh post-start.sh; fi

        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
