apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-worker.fullname" . }}
  labels:
    {{- include "laravel-worker.labels" . | nindent 4 }}
    laravel.com/pod-type: worker
    laravel.com/worker-name: {{ include "laravel-worker.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-worker.selectorLabels" . | nindent 6 }}
      laravel.com/pod-type: worker
      laravel.com/worker-name: {{ include "laravel-worker.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-worker.selectorLabels" . | nindent 8 }}
        laravel.com/pod-type: worker
        laravel.com/worker-name: {{ include "laravel-worker.fullname" . }}
    spec:
      volumes:
        - name: env
          secret:
            secretName: {{ if .Values.app.envSecretName }} {{ .Values.app.envSecretName }} {{ else }} {{ .Release.Name }}-env {{ end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "laravel-worker.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              {{- with .Values.app.command }}
              {{- range . }}
              {{ . }}
              {{- end }}
              {{- end }}
          volumeMounts:
            - name: env
              mountPath: /tmp/.env
              subPath: .env
            {{- with .Values.app.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.service.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- with .Values.app.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /tmp/.env /var/www/html/.env && cd /var/www/html && if [ -f post-start.sh ]; then sh post-start.sh; fi

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
