{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "laravel-worker.fullname" . }}
  labels:
    {{- include "laravel-worker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "laravel-worker.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "laravel-worker.serviceAccountName" . }}
{{- end }}
