apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-mysql
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  mysql-prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus-MySQL
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc.cluster.local:9090
        isDefault: false
        editable: true
        jsonData:
          timeInterval: "30s"